### ISSUE TITLE
The given APK crashes...

### ISSUE THREAD

**Issue by Wicpar** [endragor/cpal-android-test#1]
The Apk in the repository crashes...

I have a 64 bit android. The issue comes from Oboe not being able to load a dynamic symbol properly.
No idea how to solve it.

**Comment by endragor** [comment]
This isn't much information to work with. Which Android version do you have? As I know, there were problems with Android 11 that were fixed after this APK was built. Also, Android support is already merged into cpal/rodio, so you should be able to test everything yourself on the latest version of those crates.

**Comment by Wicpar** [comment]
Yes it is android 11
The issue is the .so not loading due to an unfindable symbol during dlopen: _ZTVN10cxxabiv117class_type_infoE
The issue persists in the latest version of cpal and oboe-rs.

Both of their demo projects and pre-built apks have the same issue.

Right now the only viable option I have is using the opensl-es bindings directly...
